version: '2'
services:
    audit_checklist-app:
        image: audit_checklist
        external_links:
            - audit_checklist-postgresql:postgresql
            - audit_checklist-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/audit_checklist
            - JHIPSTER_SLEEP=10
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    audit_checklist-postgresql:
        container_name: audit_checklist-postgresql
        image: postgres:9.5.3
        environment:
            - POSTGRES_USER=audit_checklist
            - POSTGRES_PASSWORD=
    audit_checklist-elasticsearch:
        container_name: audit_checklist-elasticsearch
        image: elasticsearch:1.7.5
    
    checklist-app:
        image: checklist
        external_links:
            - checklist-postgresql:postgresql
            - checklist-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/checklist
            - JHIPSTER_SLEEP=10
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    checklist-postgresql:
        container_name: checklist-postgresql
        image: postgres:9.5.3
        environment:
            - POSTGRES_USER=checklist
            - POSTGRES_PASSWORD=
    checklist-elasticsearch:
        container_name: checklist-elasticsearch
        image: elasticsearch:1.7.5
    
    gateway-app:
        image: gateway
        external_links:
            - gateway-postgresql:postgresql
            - gateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    gateway-postgresql:
        container_name: gateway-postgresql
        image: postgres:9.5.3
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    gateway-elasticsearch:
        container_name: gateway-elasticsearch
        image: elasticsearch:1.7.5
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
